version: '3'

services:
   tservice:
      image: docker.io/letniy/tservice:latest
      ports:
         - "8085:8085"
      volumes:
         - ./configs:/configs
         - ./responses:/responses
      networks:
         app_net:
      entrypoint: ["/bin/app", "-config", "/configs/config.yml", "-responsePath", "/responses", "-port", "8085"]

networks:
   app_net:
      driver: bridge