responses:
   response1:
      path: /lorem/ipsum
      definition:
         status_code: 200
         response: '{"hello":"TService Awesome!"}'
         headers:
            - Content-Type:application/json
            - x-version:321
   response2:
      path: /lorem
      definition:
         status_code: 200
         response_file: lorem.json
      slowness:
         chance: 30
         duration: 5s
   response3:
      path: /lorem/error
      definition:
         status_code: 200
         response_file: lorem.json
         headers:
            - Content-Type:application/json
      error:
         chance: 10
         status_code: 500
